<?php

namespace App\Http\Requests\Sap;

use Illuminate\Database\Schema\Builder;
use Illuminate\Foundation\Http\FormRequest;

class Salesorder extends FormRequest {

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize() {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public static function rules() {
        $length = Builder::$defaultStringLength;
        return [
                'SalesOrderNumber' => 'required|string|digits:10',
                'SalesOrg' => 'required|string|digits:4',
                'DistrChann' => 'required|string|digits:2',
                'SalesOffice' => 'required|string|digits:4',
                'Division' => 'required|string|digits:2',
                'Plant' => 'required|string|digits:4',
                'ShippingPlant' => 'required|string|digits:4',
                'DocumentCategory' => 'required|string|size:1|alpha',
                'DocumentType' => 'required|string|size:3|alpha_num',
                'OrderReason' => 'required|string|digits:3',
                'NetValue' => 'required|numeric|between:0,99999999.99',
                'DocumentCurrency' => 'required|string|size:3|alpha',
                'CustomerPurchaseOrderNumber' => 'required|string|digits:5',
                'CustomerPurchaseOrderType' => 'nullable|string|max:' . $length,
                'CustomerPurchaseOrderDate' => 'required|string|size:10|date_format:Y-m-d',
                'RequestedDeliveryDate' => 'required|string|size:10|date_format:Y-m-d',
                'NonStandardProduct' => 'required|boolean',
                'HeaderNote1' => 'nullable|string|max:' . $length,
                'HeaderNote2' => 'nullable|string|max:' . $length,
                'HeaderNote3' => 'nullable|string|max:' . $length,
                'HeaderNote4' => 'nullable|string|max:' . $length,
                'OtherContractualStipulations' => 'nullable|string|max:' . $length,
                'SoldToCustomer' => 'required|array',
                'SoldToCustomer.CustomerNumber' => 'required|string|digits:10',
                'SoldToCustomer.Country' => 'required|string|size:2|alpha',
                'SoldToCustomer.Name1' => 'required|string|max:' . $length,
                'SoldToCustomer.Name2' => 'nullable|string|max:' . $length,
                'SoldToCustomer.City' => 'required|string|max:' . $length,
                'SoldToCustomer.PostalCode' => 'required|string|digits:5',
                'SoldToCustomer.Region' => 'required|string|digits:2',
                'SoldToCustomer.StreetAddress' => 'required|string|max:' . $length,
                'SoldToCustomer.LocationNumberPart1' => 'required|string|digits:7',
                'SoldToCustomer.LocationNumberPart2' => 'required|string|digits:5',
                'Items' => 'required|array',
                'Items.*.ItemNumber' => 'required|string|digits:6|distinct',
                'Items.*.Material' => 'required|string|size:15|regex: /[\d]{6}-[\d]{4}-[\d]{3}/',
                'Items.*.MaterialGroup' => 'required|string|digits:8',
                'Items.*.ShortText' => 'required|string|max:' . $length,
                'Items.*.RequiredQuantity' => 'required|numeric|between:0,99999999.99',
                'Items.*.RequiredQuantityUnit' => 'nullable|string|alpha|max:' . $length,
                'Items.*.Quantity' => 'required|numeric|between:0,99999999.99',
                'Items.*.QuantityUnit' => 'nullable|string|alpha|max:' . $length,
                'Items.*.SerialNumber' => 'nullable|string|max:' . $length,
                'Items.*.HigherLevelItemNumber' => 'required|string|digits:6',
                'Items.*.RejectionReason' => 'nullable|string|max:' . $length,
                'Items.*.ItemCategory' => 'required|string|size:4|alpha_num',
                'Items.*.ItemType' => 'nullable|string|alpha|max:' . $length,
                'Items.*.IncoTerms1' => 'required|string|alpha|max:' . $length,
                'Items.*.IncoTerms2' => 'required|string|max:' . $length,
                'Items.*.ScheduleLines' => 'nullable|string|max:' . $length,
                'Partners' => 'required|array',
                'Partners.*.ItemNumber' => 'required|string|digits:6',
                'Partners.*.PartnerFunction' => 'required|string|size:2|alpha_num',
                'Partners.*.CustomerNumber' => 'required|string|max:10|alpha_num',
                'Partners.*.Country' => 'nullable|string|size:2|alpha',
                'Partners.*.Name1' => 'nullable|string|max:' . $length,
                'Partners.*.Name2' => 'nullable|string|max:' . $length,
                'Partners.*.City' => 'nullable|string|max:' . $length,
                'Partners.*.PostalCode' => 'nullable|string|digits:5',
                'Partners.*.Region' => 'nullable|string|digits:2',
                'Partners.*.StreetAddress' => 'nullable|string|max:' . $length,
                'Partners.*.LocationNumberPart1' => 'nullable|string|digits:7',
                'Partners.*.LocationNumberPart2' => 'nullable|string|digits:5',
        ];
    }

}

/*
     * Sample Salesorder 2017-12-01
     */

//    {
//    "CustomerOrderNumber" : "1027502842",
//    "SalesOrderNumber" : "1027502842",
//    "SalesOrg" : "0113",
//    "DistrChann" : "02",
//    "SalesOffice" : "0112",
//    "Division" : "60",
//    "Plant" : "1014",
//    "ShippingPlant" : "1014",
//    "SoldToCustomer" : {
//        "ItemNumber" : null,
//        "PartnerFunction" : null,
//        "CustomerNumber" : "0000042217",
//        "Country" : "DE",
//        "Name1" : "VW AG",
//        "Name2" : "Werk Kassel",
//        "City" : "Baunatal",
//        "PostalCode" : "34225",
//        "Region" : "06",
//        "StreetAddress" : "Dr.Rudolf-Leiding Platz 1",
//        "LocationNumberPart1" : "0000000",
//        "LocationNumberPart2" : "00000"
//    },
//    "SoldTo" : "0000042217",
//    "SoldToName" : null,
//    "DocumentCategory" : "L",
//    "DocumentType" : "ZL2",
//    "OrderReason" : "220",
//    "NetValue" : 2887.44,
//    "DocumentCurrency" : "EUR",
//    "CustomerPurchaseOrderNumber" : "66568",
//    "CustomerPurchaseOrderType" : null,
//    "CustomerPurchaseOrderDate" : "2017-09-26",
//    "RequestedDeliveryDate" : "2017-10-18",
//    "NonStandardProduct" : false,
//    "HeaderNote1" : null,
//    "HeaderNote2" : null,
//    "HeaderNote3" : null,
//    "HeaderNote4" : null,
//    "OtherContractualStipulations" : "Achtung - kundenspezifische Standards beachten - 000000-1109-708 Option Schließsystem -VW Achtung - kundenspezifische Standards beachten - 000000-1109-708 Option Schließsystem -VW",
//    "Items" : [ 
//        {
//            "ItemNumber" : "000005",
//            "Material" : "600667-9904-700",
//            "MaterialGroup" : "21170400",
//            "ShortText" : {"de":"Messkopf UP-SCAN 'GOLD'AT(Gold für Gold)","en":"Probe head UP-SCAN asdfasd",
//            "RequiredQuantity" : 0.0,
//            "RequiredQuantityUnit" : "ST",
//            "Quantity" : 0.0,
//            "QuantityUnit" : "ST",
//            "SerialNumber" : null,
//            "HigherLevelItemNumber" : "000000",
//            "RejectionReason" : null,
//            "ItemCategory" : "ZL2T",
//            "ItemType" : "B",
//            "CustomerPurchaseOrderNumber" : "66568",
//            "CustomerPurchaseOrderType" : null,
//            "CustomerPurchaseOrderDate" : "2017-09-26",
//            "IncoTerms1" : "EXW",
//            "IncoTerms2" : "-",
//            "Plant" : "1014",
//            "ScheduleLines" : null
//        }, 
//        {
//            "ItemNumber" : "000010",
//            "Material" : "999999-9999-999",
//            "MaterialGroup" : "35010500",
//            "ShortText" : { "de": "aSdhfasdfkalsdfklaöjsdf", "en": "aSdhfasdfkalsdfklaöjsdf"}
//            "RequiredQuantity" : 0.0,
//            "RequiredQuantityUnit" : "ST",
//            "Quantity" : 0.0,
//            "QuantityUnit" : "ST",
//            "SerialNumber" : null,
//            "HigherLevelItemNumber" : "000005",
//            "RejectionReason" : null,
//            "ItemCategory" : "ZL2N",
//            "ItemType" : null,
//            "CustomerPurchaseOrderNumber" : "66568",
//            "CustomerPurchaseOrderType" : null,
//            "CustomerPurchaseOrderDate" : "2017-09-26",
//            "IncoTerms1" : "EXW",
//            "IncoTerms2" : "-",
//            "Plant" : "1014",
//            "ScheduleLines" : null
//        }, 
//        {
//            "ItemNumber" : "000020",
//            "Material" : "600667-0034-000",
//            "MaterialGroup" : "35011300",
//            "ShortText" : "Halter",
//            "RequiredQuantity" : 0.0,
//            "RequiredQuantityUnit" : "ST",
//            "Quantity" : 0.0,
//            "QuantityUnit" : "ST",
//            "SerialNumber" : null,
//            "HigherLevelItemNumber" : "000000",
//            "RejectionReason" : null,
//            "ItemCategory" : "ZL2N",
//            "ItemType" : null,
//            "CustomerPurchaseOrderNumber" : "66568",
//            "CustomerPurchaseOrderType" : null,
//            "CustomerPurchaseOrderDate" : "2017-09-26",
//            "IncoTerms1" : "EXW",
//            "IncoTerms2" : "-",
//            "Plant" : "1014",
//            "ScheduleLines" : null
//        }, 
//        {
//            "ItemNumber" : "000030",
//            "Material" : "600664-0046-000",
//            "MaterialGroup" : "35040400",
//            "ShortText" : "DÄMPFUNGSPLATTE",
//            "RequiredQuantity" : 0.0,
//            "RequiredQuantityUnit" : "ST",
//            "Quantity" : 0.0,
//            "QuantityUnit" : "ST",
//            "SerialNumber" : null,
//            "HigherLevelItemNumber" : "000000",
//            "RejectionReason" : null,
//            "ItemCategory" : "ZL2N",
//            "ItemType" : null,
//            "CustomerPurchaseOrderNumber" : "66568",
//            "CustomerPurchaseOrderType" : null,
//            "CustomerPurchaseOrderDate" : "2017-09-26",
//            "IncoTerms1" : "EXW",
//            "IncoTerms2" : "-",
//            "Plant" : "1014",
//            "ScheduleLines" : null
//        }, 
//        {
//            "ItemNumber" : "000040",
//            "Material" : "600664-0045-000",
//            "MaterialGroup" : "35040400",
//            "ShortText" : "DÄMPFUNGSPLATTE",
//            "RequiredQuantity" : 0.0,
//            "RequiredQuantityUnit" : "ST",
//            "Quantity" : 0.0,
//            "QuantityUnit" : "ST",
//            "SerialNumber" : null,
//            "HigherLevelItemNumber" : "000000",
//            "RejectionReason" : null,
//            "ItemCategory" : "ZL2N",
//            "ItemType" : null,
//            "CustomerPurchaseOrderNumber" : "66568",
//            "CustomerPurchaseOrderType" : null,
//            "CustomerPurchaseOrderDate" : "2017-09-26",
//            "IncoTerms1" : "EXW",
//            "IncoTerms2" : "-",
//            "Plant" : "1014",
//            "ScheduleLines" : null
//        }, 
//        {
//            "ItemNumber" : "000050",
//            "Material" : "630665-8300-000",
//            "MaterialGroup" : "35010500",
//            "ShortText" : "Tarierung",
//            "RequiredQuantity" : 0.0,
//            "RequiredQuantityUnit" : "ST",
//            "Quantity" : 0.0,
//            "QuantityUnit" : "ST",
//            "SerialNumber" : null,
//            "HigherLevelItemNumber" : "000000",
//            "RejectionReason" : null,
//            "ItemCategory" : "ZL2N",
//            "ItemType" : null,
//            "CustomerPurchaseOrderNumber" : "66568",
//            "CustomerPurchaseOrderType" : null,
//            "CustomerPurchaseOrderDate" : "2017-09-26",
//            "IncoTerms1" : "EXW",
//            "IncoTerms2" : "-",
//            "Plant" : "1014",
//            "ScheduleLines" : null
//        }, 
//        {
//            "ItemNumber" : "000060",
//            "Material" : "000000-1019-221",
//            "MaterialGroup" : "81401000",
//            "ShortText" : "LP Verdrahtung UP-VAST intern Prog-ID",
//            "RequiredQuantity" : 0.0,
//            "RequiredQuantityUnit" : "ST",
//            "Quantity" : 0.0,
//            "QuantityUnit" : "ST",
//            "SerialNumber" : null,
//            "HigherLevelItemNumber" : "000000",
//            "RejectionReason" : null,
//            "ItemCategory" : "ZL2N",
//            "ItemType" : null,
//            "CustomerPurchaseOrderNumber" : "66568",
//            "CustomerPurchaseOrderType" : null,
//            "CustomerPurchaseOrderDate" : "2017-09-26",
//            "IncoTerms1" : "EXW",
//            "IncoTerms2" : "-",
//            "Plant" : "1014",
//            "ScheduleLines" : null
//        }, 
//        {
//            "ItemNumber" : "000070",
//            "Material" : "600004-0300-000",
//            "MaterialGroup" : "15000000",
//            "ShortText" : "Stundensatz Arbeit",
//            "RequiredQuantity" : 0.0,
//            "RequiredQuantityUnit" : "STD",
//            "Quantity" : 0.0,
//            "QuantityUnit" : "STD",
//            "SerialNumber" : null,
//            "HigherLevelItemNumber" : "000000",
//            "RejectionReason" : null,
//            "ItemCategory" : "ZL2Z",
//            "ItemType" : null,
//            "CustomerPurchaseOrderNumber" : "66568",
//            "CustomerPurchaseOrderType" : null,
//            "CustomerPurchaseOrderDate" : "2017-09-26",
//            "IncoTerms1" : "EXW",
//            "IncoTerms2" : "-",
//            "Plant" : "1014",
//            "ScheduleLines" : null
//        }
//    ],
//    "Partners" : [ 
//        {
//            "ItemNumber" : "000000",
//            "PartnerFunction" : "1C",
//            "CustomerNumber" : "0000957293",
//            "Country" : null,
//            "Name1" : null,
//            "Name2" : null,
//            "City" : null,
//            "PostalCode" : null,
//            "Region" : null,
//            "StreetAddress" : null,
//            "LocationNumberPart1" : null,
//            "LocationNumberPart2" : null
//        }, 
//        {
//            "ItemNumber" : "000000",
//            "PartnerFunction" : "1D",
//            "CustomerNumber" : "0000952810",
//            "Country" : null,
//            "Name1" : null,
//            "Name2" : null,
//            "City" : null,
//            "PostalCode" : null,
//            "Region" : null,
//            "StreetAddress" : null,
//            "LocationNumberPart1" : null,
//            "LocationNumberPart2" : null
//        }, 
//        {
//            "ItemNumber" : "000000",
//            "PartnerFunction" : "AG",
//            "CustomerNumber" : "0000042217",
//            "Country" : "DE",
//            "Name1" : "VW AG",
//            "Name2" : "Werk Kassel",
//            "City" : "Baunatal",
//            "PostalCode" : "34225",
//            "Region" : "06",
//            "StreetAddress" : "Dr.Rudolf-Leiding Platz 1",
//            "LocationNumberPart1" : "0000000",
//            "LocationNumberPart2" : "00000"
//        }, 
//        {
//            "ItemNumber" : "000000",
//            "PartnerFunction" : "RE",
//            "CustomerNumber" : "0000042217",
//            "Country" : "DE",
//            "Name1" : "VW AG",
//            "Name2" : "Werk Kassel",
//            "City" : "Baunatal",
//            "PostalCode" : "34225",
//            "Region" : "06",
//            "StreetAddress" : "Dr.Rudolf-Leiding Platz 1",
//            "LocationNumberPart1" : "0000000",
//            "LocationNumberPart2" : "00000"
//        }, 
//        {
//            "ItemNumber" : "000000",
//            "PartnerFunction" : "RG",
//            "CustomerNumber" : "0000042217",
//            "Country" : "DE",
//            "Name1" : "VW AG",
//            "Name2" : "Werk Kassel",
//            "City" : "Baunatal",
//            "PostalCode" : "34225",
//            "Region" : "06",
//            "StreetAddress" : "Dr.Rudolf-Leiding Platz 1",
//            "LocationNumberPart1" : "0000000",
//            "LocationNumberPart2" : "00000"
//        }, 
//        {
//            "ItemNumber" : "000000",
//            "PartnerFunction" : "WE",
//            "CustomerNumber" : "0000042217",
//            "Country" : "DE",
//            "Name1" : "VW AG",
//            "Name2" : "Werk Kassel",
//            "City" : "Baunatal",
//            "PostalCode" : "34225",
//            "Region" : "06",
//            "StreetAddress" : "Dr.Rudolf-Leiding Platz 1",
//            "LocationNumberPart1" : "0000000",
//            "LocationNumberPart2" : "00000"
//        }, 
//        {
//            "ItemNumber" : "000000",
//            "PartnerFunction" : "ZE",
//            "CustomerNumber" : "0000042217",
//            "Country" : "DE",
//            "Name1" : "VW AG",
//            "Name2" : "Werk Kassel",
//            "City" : "Baunatal",
//            "PostalCode" : "34225",
//            "Region" : "06",
//            "StreetAddress" : "Dr.Rudolf-Leiding Platz 1",
//            "LocationNumberPart1" : "0000000",
//            "LocationNumberPart2" : "00000"
//        }, 
//        {
//            "ItemNumber" : "000000",
//            "PartnerFunction" : "ZI",
//            "CustomerNumber" : "CZ78446",
//            "Country" : null,
//            "Name1" : null,
//            "Name2" : null,
//            "City" : null,
//            "PostalCode" : null,
//            "Region" : null,
//            "StreetAddress" : null,
//            "LocationNumberPart1" : null,
//            "LocationNumberPart2" : null
//        }
//    ]
//}
